# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Выделение памяти для JVM и кодировка
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Кэширование конфигурации для ускорения сборки
org.gradle.configuration-cache=true

# Стиль кода Kotlin
kotlin.code.style=official

# Поддержка AndroidX (критично для Jetpack Compose, Koin и современных библиотек)
android.useAndroidX=true
android.builtInKotlin=false